# Generated by Django 2.2 on 2019-05-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('post', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
